baseURL: "https://blog.lc6chang.com"

# [en, zh-cn, fr, pl, ...] determines default content language
defaultContentLanguage: "zh-cn"

theme: "LoveIt"

# whether to use robots.txt
enableRobotsTXT: true
# whether to use emoji code
enableEmoji: true

languages:
  en:
    weight: 1
    languageCode: "en"
    languageName: "English"
    # whether to include Chinese/Japanese/Korean
    hasCJKLanguage: false
    # default amount of posts in each pages
    paginate: 12
    # copyright description used only for seo schema
    copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License."
    title: "lc6chang's Blog"
    menu:
      main:
        - identifier: "posts"
          pre: ""
          post: ""
          name: "Posts"
          url: "/posts/"
          title: ""
          weight: 1
        - identifier: "categories"
          pre: ""
          post: ""
          name: "Categories"
          url: "/categories/"
          title: ""
          weight: 2
        - identifier: "tags"
          pre: ""
          post: ""
          name: "Tags"
          url: "/tags/"
          title: ""
          weight: 3
        - identifier: "about"
          pre: ""
          post: ""
          name: "About"
          url: "/about/"
          title: ""
          weight: 4
        - identifier: "github"
          pre: "<i class='fab fa-github fa-fw'></i>"
          post: ""
          name: ""
          url: "https://github.com/lc6chang/lc6chang-blog"
          title: "GitHub"
          weight: 5
    params:
      header:
        title:
          name: "lc6chang's Blog"
      description: "This is lc6chang's Blog"
      keywords: ["lc6chang", "blog", "technology", "software engineering"]
      social:
        GitHub: "lc6chang"
        Linkedin: "chang-liu-1a607b17a"
        Email: "lc6chang@gmail.com"
        Stackoverflow: "10839541"
      home:
        profile:
          enable: true
          gravatarEmail: "1061974239@qq.com"
          title: ""
          subtitle: "A Software Engineer's Personal Blog"
          typeit: true
          social: true
        posts:
          enable: true
          paginate: 6

  zh-cn:
    weight: 2
    languageCode: "zh-CN"
    languageName: "简体中文"
    hasCJKLanguage: true
    paginate: 12
    # copyright description used only for seo schema
    copyright: "This work is licensed under a Creative Commons Attribution-NonCommercial-NoDerivatives 4.0 International License."
    title: "lc6chang的博客"
    menu:
      main:
        - identifier: "posts"
          pre: ""
          post: ""
          name: "所有文章"
          url: "/posts/"
          title: ""
          weight: 1
        - identifier: "categories"
          pre: ""
          post: ""
          name: "分类"
          url: "/categories/"
          title: ""
          weight: 2
        - identifier: "tags"
          pre: ""
          post: ""
          name: "标签"
          url: "/tags/"
          title: ""
          weight: 3
        - identifier: "about"
          pre: ""
          post: ""
          name: "关于"
          url: "/about/"
          title: ""
          weight: 4
        - identifier: "github"
          pre: "<i class='fab fa-github fa-fw'></i>"
          post: ""
          name: ""
          url: "https://github.com/lc6chang/lc6chang-blog"
          title: "GitHub"
          weight: 5
    params:
      header:
        title:
          name: "lc6chang的博客"
      description: "lc6chang的个人博客"
      keywords: ["lc6chang", "博客", "计算机科学与技术", "软件工程"]
      social:
        GitHub: "lc6chang"
        Linkedin: "chang-liu-1a607b17a"
        Email: "lc6chang@gmail.com"
        Stackoverflow: "10839541"
      home:
        profile:
          enable: true
          gravatarEmail: "1061974239@qq.com"
          title: ""
          subtitle: "一个码农的个人博客"
          typeit: true
          social: true
        posts:
          enable: true
          paginate: 6

params:
  version: "0.2.X"
  # site default theme ("light", "dark", "auto")
  defaultTheme: "auto"
  header:
    # desktop header mode ("fixed", "normal", "auto")
    desktopMode: "fixed"
    # mobile header mode ("fixed", "normal", "auto")
    mobileMode: "auto"
  footer:
    enable: true
    custom: ""
    hugo: true
    copyright: true
    author: true
    since: 2020
    license: |
      <a rel="license" href="http://creativecommons.org/licenses/by-nc-nd/4.0/">CC BY-NC-ND 4.0</a>
  typeit:
    # typing speed between each step (measured in milliseconds)
    speed: 100
    # blinking speed of the cursor (measured in milliseconds)
    cursorSpeed: 1000
    # character used for the cursor (HTML format is supported)
    cursorChar: "|"
    # cursor duration after typing finishing (measured in milliseconds, "-1" means unlimited)
    duration: -1
  analytics:
    enable: true
    google:
      id: "UA-153223502-1"

author:
  name: "lc6chang"
  email: "lc6chang@gmail.com"
